### ISSUE TITLE
About the file of ColorOctree.h

### ISSUE THREAD

**Issue by jiahuazhu** [xiaoxifuhongse/ORB-SLAM-RGBD-with-Octomap#1]
Hello, dear author, I'm trying to compile your project on my computer，  when I build the ORB_SLAM2, an error message like this appears:catkin_ws/src/ORB_SLAM2/include/MapDrawer.h:31:33: fatal error: octomap/ColorOcTree.h: 没有那个文件或目录.
I wonder if you have not uploaded this document. If not, could you please upload it? Thank you very much for your work and answer。

**Comment by xiaoxifuhongse** [comment]
I am sorry, you can compile octomap by yourself, and then you can include your directory

**Comment by jiahuazhu** [comment]
Ok, thank you very much for your reply and thank you again for your work!
